### ISSUE TITLE
I ran 'train_dop.py'. it is giving errors.

### ISSUE THREAD

**Issue by PalgunaGopireddy** [Xiangyu-Gao/Radar-multiple-perspective-object-detection#13]
I ran `python train_dop.py -m C3D` it is raising error:
```
No data augmentation
Number of sequences to train: 1
Training files length: 111
Window size: 16
Number of epoches: 100
Batch size: 3
Number of iterations in each epoch: 37
Cyclic learning rate
load fail
Traceback (most recent call last):
  File "G:\Palguna\github\Radar-multiple-perspective-object-detection-main\dataLoader\CRDatasets.py", line 102, in __getitem__
    load_rv = np.load(path_rv)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\numpy\lib\npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './template_files/train_test_data/2019_04_30\\2019_04_30_pbms002\\RA_NPY\\%04d\\%06d.npy/RV_NPY/000512.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Palguna\github\Radar-multiple-perspective-object-detection-main\train_dop.py", line 204, in <module>
    for iter, loaded_data in enumerate(dataloader):
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\Palguna\github\Radar-multiple-perspective-object-detection-main\dataLoader\CRDatasets.py", line 115, in __getitem__
    raise ValueError
ValueError
```
I guess there is a serious problem of naming the folders.
Even when I ran` python prepare_data.py -m train -dd './data/' ` It has created dataset under `.` folder with subfolder `data`.
I had to rename `--dd` argument default as `data` instead of `./data/` and run ` python prepare_data.py -m train`  without using `-dd` command to create dataset under `data` folder

How to resolve this error.

**Comment by Xiangyu-Gao** [comment]
It seems to me the issue is that the data in this directory  ' ./template_files/train_test_data' can not be detected by the program. So you may check if data under this directory exists.

**Comment by Xiangyu-Gao** [comment]
by the way, the directory does not look good to me. "\\RA_NPY\\%04d\\%06d.npy/RV_NPY/000512.npy" The RA_NPY and RV_NPY should NOT be in the same directory. 
You may want to debug what causes that. I have never met/heard this issue.

**Comment by PalgunaGopireddy** [comment]
Let me check. I will get back to you.

**Comment by PalgunaGopireddy** [comment]
Hi. The above error caused due to line 93 in CRDatasets.py `root_path = path.split('/RA_NPY')[0] `
It worked when changing backslash `/` to `\`. i.e.  `root_path = path.split('\RA_NPY')[0] `

I guess it is due to the issue of addressing convention. 
Like I told in the question description also:  using `python prepare_data.py -m train -dd './data/'` created dataset under `.` folder with subfolder `data`.I had to rename `--dd` argument default in `prepare_data.py`  as `data` instead of `./data/` and run  `python prepare_data.py -m train` without using `-dd` command to create dataset under `data` folder.

**Comment by Xiangyu-Gao** [comment]
That makes sense. I guess you are using the Windows system, the path of which (for example, '/', './') is a little different from the Linux system I used.
